name: "Doxygen Build"
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - rel-*
    paths:
      - src/**
  pull_request:
jobs:
  build:
    name: Generate API docs
    runs-on: [ "self-hosted", "1ES.Pool=onnxruntime-genai-Ubuntu2204-AMD-CPU" ]
    steps:
      - uses: actions/checkout@v4
      - name: Install doxygen and dependencies
        run: |
          sudo apt update
          sudo apt-get install libclang-dev
          sudo apt-get install libclang-cpp14
          wget https://www.doxygen.nl/files/doxygen-1.9.8.linux.bin.tar.gz
          tar xvzf doxygen-1.9.8.linux.bin.tar.gz

      - name: Run C/C++ doxygen
        run: |
          cd src/
          ../doxygen-1.9.8/bin/doxygen Doxyfile

      - name: Run CSharp doxygen
        run: |
          cd src/csharp/
          ../../doxygen-1.9.8/bin/doxygen Doxyfile_csharp.cfg

      - name: Run Java doxygen
        run: |
          cd src/java/
          ../../doxygen-1.9.8/bin/doxygen Doxyfile_java.cfg

      - name: Run Objective-C doxygen
        run: |
          cd src/objectivec/
          ../../doxygen-1.9.8/bin/doxygen Doxyfile_objc.cfg

      - name: Run API diff
        run: |
          python -m pip install -U jsonpickle
          python ./tools/ci_build/validate_doxygen_xml.py \
            --cxx-output-dir ./src/cxx_dox \
            --java-output-dir ./src/java/java_dox \
            --csharp-output-dir ./src/csharp/csharp_dox \
            --objc-output-dir ./src/objectivec/objc_dox
