name: "Doxygen Build"
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - rel-*
    paths:
      - src/**
  pull_request:
jobs:
  build:
    name: Generate API docs
    runs-on: [ "self-hosted", "1ES.Pool=onnxruntime-genai-Ubuntu2204-AMD-CPU" ]
    steps:
      - uses: actions/checkout@v4
      - name: Install doxygen and dependencies
        run: |
          sudo apt update
          sudo apt-get install libclang-dev
          sudo apt-get install libclang-cpp14
          wget https://www.doxygen.nl/files/doxygen-1.9.8.linux.bin.tar.gz
          tar xvzf doxygen-1.9.8.linux.bin.tar.gz

      - name: Run C/C++ doxygen
        run: |
          doxygen-1.9.8/bin/doxygen src/Doxyfile

      - name: Run CSharp doxygen
        run: |
          doxygen-1.9.8/bin/doxygen src/csharp/Doxyfile_csharp.cfg

      - name: Run Java doxygen
        run: |
          doxygen-1.9.8/bin/doxygen src/java/Doxyfile_java.cfg

